
version: '3.1'

networks:
  dev-network:

#
# If you don't assign an external volume then a volume will be created on first use.
# The name for the volume will be prefixed with this files parent directory name:
# php-fpm-nginx-environment_dbase
#
# To include an external volume use external: true
volumes:
  dbase:
    # external: true

services:
  mariadb:
    build:
      context: ./mariadb
    tty: true
    # environment variables can be included in .env file or accessed from system ENV 
    environment: 
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes: 
      - type: volume
        source: dbase
        target: /var/lib/mysql
    networks:
      - dev-network
    restart: always

  adminer:
      image: adminer
      restart: always
      expose: 
          - 8080
      # accessed through port 8880 on host
      ports: 
          - "8880:8080"
      networks:
        - dev-network
  # docker-php-cli:
  #   build: 
  #     context: ./php-cli
  #   tty: true
  #   volumes:
  #     - ./app:/var/www
  #   networks:
  #     - web-network

  nginx:
    build: 
      context: ./nginx-server
    ports:
      - "8001:80"
    tty: true
    volumes:
      - ./app:/var/www
      - ./nginx-server/conf.d:/etc/nginx/conf.d
    networks:
      - dev-network

  php-fpm:
    build: 
      context: ./php-fpm
    tty: true
    volumes:
      - ./app:/var/www
    networks:
      - dev-network
